### ISSUE TITLE
Another and more complete translation toolkit written in Python and under GPL already exists

### ISSUE THREAD

**Issue by KennethNielsen** [pyg3t/pyg3t#16]
Everything here seems to be double work.

The programs in PyG3T seems to offer nothing that is not already offered by The Translate Toolkit:
Homepage: http://translate.sourceforge.net/wiki/toolkit/index
Download: http://sourceforge.net/projects/translate/files/Translate%20Toolkit/
API: http://translate.sourceforge.net/doc/api/

The Translate Toolkit is written in Python and under GPL like PyG3T, so it would be possible to build tools with many more features than currently present in PyG3T using The Translate Toolkit's API if needed.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2011-12-30T10:52:34Z
 * owner: byrial-t
 * the launchpad url was https://bugs.launchpad.net/bugs/910059

**Comment by KennethNielsen** [comment]
(by askhl)
We know about translate toolkit.  Some of the very simple scripts are double work.  Sometimes we run into some special task that has to be done, but isn't straightforward with other tools.  Then we script it in pyg3t.  pyg3t also includes some "general" utilities for everyday use but doesn't at all attempt to be as general as translate-toolkit.  The python interfaces of the two packages are also quite different.

**Comment by KennethNielsen** [comment]
(by byrial-t)
Hi Ask,

You said "Some of the very simple scripts are double work."

Very much of pyG3T is indeed double work:

- gtcat can recode po-files, but so can poreencode
- gtcheckargs can check commandline options, but so can pofilter
- gtgrep can search po-files, but so can pogrep
- gtmerge can merge po-files, but so can pomerge
- gtxml can check xml code, but so can pofilter
- poabc can check for some errors, but so can pofilter which have many more test than poabc
- poselect can  filter messages based on status, but so can posplit although not for plural forms.

What may be unique for pyG3T is:
- gtcompare
- podiff
- popatch

So pyG3T's speciality is to compare and find differences between pofiles. Why not concentrate on that instead doubling what already is done and works well?

BTW: I know it doesn't belong here but gtxml crashed when I tested it for comparison with pofilter:

$ gtxml da.po
Traceback (most recent call last):
  File "/usr/bin/gtxml", line 5, in <module>
    gtxml.main()
  File "/usr/lib/python2.7/dist-packages/pyg3t/gtxml.py", line 160, in main
    for bad_msg, err in gtxml.check_msgs(cat):
  File "/usr/lib/python2.7/dist-packages/pyg3t/gtxml.py", line 53, in check_msgs
    self.check_msg(msg)
  File "/usr/lib/python2.7/dist-packages/pyg3t/gtxml.py", line 46, in check_msg
    self.check_string(msgstr)
  File "/usr/lib/python2.7/dist-packages/pyg3t/gtxml.py", line 25, in check_string
    xmlstring = self._filter(string)
  File "/usr/lib/python2.7/dist-packages/pyg3t/gtxml.py", line 21, in _filter
    xml = u''.join([u'<xml>', string.replace(u'\\"', u'"'), u'</xml>'])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 21: ordinal not in range(128)

**Comment by KennethNielsen** [comment]
(by askhl)
Really these are just small scripts which get written when we want something done.

gtcat is mostly pointless but we use it for testing.

gtcheckargs is probably not perfect, but it identifies at least some important errors that the 'options' filter from Translate does not.  For example errors in short options.  They do different things.  gtcheckargs is only meant for the standard option/description lists.  It was written to find errors in coreutils (there were some, but not as many as I thought, for the record).

One of the points with gtmerge is that we want to do a few more specific things.  Like fixing the header when uploading to launchpad (very annoying to have to do that in other cases; they removed the 'import', so now a lot of manual merging must be done, and I don't think the existing tools produce a file which is ready to be uploaded back to LP), and minimizing the "paperwork" when merging translations into previous po files when uploading to TranslationProject (only the latter has been implemented because I haven't needed the former recently).

gtxml differs mostly by making it convenient, I think, to handle many files at a time.  I use it on the GNOME documentation translation tarballs particularly.

gtgrep and poabc are definitely not unique.  poabc provides a lot less output compared to pofilter.  Maybe some things will be added along the way if it turns out to be the fastest way for me or someone else to do some things.

**Comment by KennethNielsen** [comment]
(by k-nielsen81)
Thanks for reporting this. Had we not been aware of the translate toolkit already, we would certainly have appreciated being made aware of it.

However, the bottom line is that we are aware of the translate toolkit and we are knowingly, for the reasons Ask outlined and others, developing this toolkit separately despite the level of function duplicating. This means that this is not a bug, marking as invalid.

Regards Kenneth
