### ISSUE TITLE
gtxml crashes with UnicodeDecodeError

### ISSUE THREAD

**Issue by KennethNielsen** [pyg3t/pyg3t#17]
$ cat da.po
msgid ""
msgstr ""
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

msgid "<a>You did not specify the engine executable</a>"
msgstr "<a>Du angav ikke en kørbar motor<a>"
$ gtxml da.po
Traceback (most recent call last):
  File "/usr/bin/gtxml", line 5, in <module>
    gtxml.main()
  File "/usr/lib/python2.7/dist-packages/pyg3t/gtxml.py", line 160, in main
    for bad_msg, err in gtxml.check_msgs(cat):
  File "/usr/lib/python2.7/dist-packages/pyg3t/gtxml.py", line 53, in check_msgs
    self.check_msg(msg)
  File "/usr/lib/python2.7/dist-packages/pyg3t/gtxml.py", line 46, in check_msg
    self.check_string(msgstr)
  File "/usr/lib/python2.7/dist-packages/pyg3t/gtxml.py", line 25, in check_string
    xmlstring = self._filter(string)
  File "/usr/lib/python2.7/dist-packages/pyg3t/gtxml.py", line 21, in _filter
    xml = u''.join([u'<xml>', string.replace(u'\\"', u'"'), u'</xml>'])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 21: ordinal not in range(128)
$

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2011-12-30T20:16:12Z
 * owner: byrial-t
 * the launchpad url was https://bugs.launchpad.net/bugs/910202

**Comment by KennethNielsen** [comment]
(by askhl)
Thanks.  This should be fixed in trunk.
