### ISSUE TITLE
poabc fails if Last-Translator contains æøå

### ISSUE THREAD

**Issue by scootergrisen** [pyg3t/pyg3t#32]
I don't know if this have been fixed already and if i'm using an old version (0.4.0) but if the last-translator header contains characters like æøå poabc will fail:

"Last-Translator: æøå\n"

    $ poabc filename.po 
    Traceback (most recent call last):
      File "/usr/local/bin/poabc", line 5, in <module>
        poabc.main()
      File "/usr/local/lib/python2.7/dist-packages/pyg3t/util.py", line 82, in main_decorator
        main()
      File "/usr/local/lib/python2.7/dist-packages/pyg3t/poabc.py", line 249, in main
        cat = parse(allfiles)
      File "/usr/local/lib/python2.7/dist-packages/pyg3t/gtparse.py", line 640, in parse
        for line in header['msgstrs'][0].split('\\n'):
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 255: ordinal not in range(128)

**Comment by askhl** [comment]
Thank you very much for reporting this.  The error has been fixed.
